# Generated by Django 3.2.5 on 2021-11-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settingName', models.CharField(max_length=250)),
                ('settingValue', models.CharField(max_length=250)),
            ],
        ),
    ]
