# Generated by Django 3.2.5 on 2021-11-18 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20211118_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategories',
            name='icon',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
